apiVersion: v1
kind: Pod
metadata:
  name: batch-worker-cuda
  labels:
    app: batch
spec:
  containers:
  - name: batch-worker-cuda
    image: sciencedata/batch_worker_cuda
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "gridfactory"
    - name: SD_UID
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: PEERS_IMAGE
      value: "sciencedata/batch_server"
    - name: PEERS
      value: ""
    - name: KEY_PASSWORD
      value: "grid"
    - name: UNENCRYPTED_KEY
      value: "true"
    - name: CUDA_VISIBLE_DEVICES_NUM
      value: "4"
    resources:
      limits:
        nvidia.com/gpu: 4
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  imagePullSecrets:
  - name: regcred
  runtimeClassName: nvidia
  nodeName: worker1
  restartPolicy: Never
