apiVersion: v1
kind: Pod
metadata:
  name: batch-server
  labels:
    app: batch
spec:
  containers:
  - name: batch-server
    image: sciencedata/batch_server
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "root"
    - name: SD_UID
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: ONLY_FROM
      value: ""
    - name: SSL_DN_HEADER
      value: ""
    - name: TRUSTED_VOS
      value: ""
    - name: RTE_URLS
      value: ""
    - name: MY_HOSTNAME
      value: ""
    - name: ADMIN_SUBJECT
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
