apiVersion: v1
kind: Pod
metadata:
  name: batch-worker
  labels:
    app: batch
spec:
  containers:
  - name: batch-worker
    image: sciencedata/batch_worker
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "gridfactory"
    - name: SD_UID
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: PEERS_IMAGE
      value: "sciencedata/batch_server"
    - name: PEERS
      value: ""
    - name: MY_VOS
      value: "https://batch/vos/default.txt"
    - name: KEY_PASSWORD
      value: "grid"
    - name: UNENCRYPTED_KEY
      value: "true"
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
