apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-caddy
  labels:
    app: ubuntu-caddy
  annotations:
    security.alpha.kubernetes.io/sysctls: net.ipv4.ping_group_range=0 2147483647
spec:
  containers:
  - name: ubuntu-caddy
    image: LOCALREGISTRY/ubuntu_jammy_caddy_sciencedata_testing
    volumeMounts:
      - name: sciencedata
        mountPath: "/root/www"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY # ask require
      value: ""
    - name: USERNAME
      value: "root"
    - name: HOME_SERVER
      value: ""
    - name: WORKING_DIRECTORY # ask require
      value: "website"
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
  restartPolicy: Never
