apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-focal
  labels:
    app: ubuntu
  annotations:
    security.alpha.kubernetes.io/sysctls: net.ipv4.ping_group_range=0 2147483647
spec:
  containers:
  - name: ubuntu-focal
    image: sciencedata/ubuntu_focal_caddy_sciencedata
    volumeMounts:
      - name: sciencedata
        mountPath: "/root/www"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "root"
    - name: HOME_SERVER
      value: ""
  restartPolicy: Never
  #nodeName: worker1
