apiVersion: v1
kind: Pod
metadata:
  name: debian-ssh-rsync
  labels:
    app: debian-ssh-rsync
    domain: dtu.dk
    user: fror
spec:
  containers:
  - name: debian-ssh-rsync
    image: codeberg.org/codeberg-infrastructure/backup
    volumeMounts:
      - name: sciencedata
        mountPath: "/data"
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "data"
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "mkdir -p /home/sciencedata/.WolframEngine/Licensing/"]
  restartPolicy: Never
