apiVersion: v1
kind: Pod
metadata:
  name: jupyter
spec:
  containers:
  - name: jupyter
    image: sciencedata/jupyter_sciencedata_custom
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: SETUP_ROOT
      value: ""
    - name: CVMFS_REPOS
      value: "atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch,unpacked.cern.ch,sft.cern.ch"
    - name: POD_HTTP_PORT
      value: "8888"
    - name: FILE
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"

