apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pytorch
spec:
  containers:
  - name: jupyter-pytorch
    image: sciencedata/jupyter_sciencedata_pytorch
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: SD_GID
      value: ""
    - name: POD_HTTP_PORT
      value: "8888"
    - name: FILE
      value: ""
    - name: CUDA_VISIBLE_DEVICES_NUM
      value: "4"
    resources:
      limits:
        nvidia.com/gpu: 4
        memory: 10Gi
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  runtimeClassName: nvidia
  nodeName: worker1

