apiVersion: v1
kind: Pod
metadata:
  name: jupyter-matlab
spec:
  containers:
  - name: jupyter-matlab
    image: sciencedata/jupyter_sciencedata_custom:3.0
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: MATLAB_LICENSE_SERVER
      value: "10.2.0.15"
    - name: MATLAB_LICENSE_PORT
      value: "1711"
    - name: MMA_LICENSE_SERVER
      value: "10.2.0.15"
    - name: SETUP_MATLAB
      value: "true"
    - name: SETUP_MATHEMATICA
      value: ""
    - name: MOUNT_SRC
      value: "/usr/local/software"
    - name: MOUNT_DEST
      value: "/usr/local/software"
    - name: POD_HTTP_PORT
      value: "8888"
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
