apiVersion: v1
kind: Pod
metadata:
  name: jupyter-mathematica
spec:
  containers:
  - name: jupyter-mathematica
    image: sciencedata/jupyter_sciencedata_custom:1.2
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: MATLAB_LICENSE_SERVER
      value: "10.2.0.15"
    - name: MATLAB_LICENSE_PORT
      value: "1711"
    - name: MMA_LICENSE_SERVER
      value: "10.2.0.15"
    - name: SETUP_MATLAB
      value: ""
    - name: SETUP_MATHEMATICA
      value: "true"
    - name: MOUNT_SRC
      value: "/usr/local/software"
    - name: MOUNT_DEST
      value: "/usr/local/software"
    - name: POD_HTTP_PORT
      value: "8888"
    - name: FILE
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "mkdir -p /home/sciencedata/.WolframEngine/Licensing/"]
          command: ["/bin/bash", "-c", "curl --insecure https://sciencedata/files/mathpass -o /home/sciencedata/.WolframEngine/Licensing/mathpass >& /dev/null || echo 'no mathpass'"]
      preStop:
        exec:
          command: ["/bin/bash","-c","[ -s /home/sciencedata/.WolframEngine/Licensing/mathpass ] && curl --insecure --upload /home/sciencedata/.WolframEngine/Licensing/mathpass https://sciencedata/files/mathpass"]
