apiVersion: v1
kind: Pod
metadata:
  name: jupyterlab-cuda
  labels:
    app: batch
spec:
  containers:
  - name: jupyterlab-cuda
    image: sciencedata/jupyterlab_sciencedata_cuda
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "sciencedata"
    - name: SD_UID
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: POD_HTTP_PORT
      value: "8888"
    - name: FILE
      value: ""
    - name: JUPYTER_ENABLE_LAB
      value: "true"
    - name: CUDA_VISIBLE_DEVICES
      value: ""
    resources:
      limits:
        nvidia.com/gpu: 2
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
    volumeMounts:
    - mountPath: /usr/local/ml
      name: nfs-claim-sciencedata-cloud-ml
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: nfs-claim-sciencedata-cloud-ml
    persistentVolumeClaim:
      claimName: nfs-10.0.0.13-cloud-ml
  runtimeClassName: nvidia
  nodeName: worker1
  restartPolicy: Never
