apiVersion: v1
kind: Pod
metadata:
  name: jupyter-matlab
spec:
  containers:
  - name: jupyter-matlab
    volumeMounts:
      - name: local
        mountPath: "/usr/local/software"
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: MMA_LICENSE_SERVER
      value: "10.2.0.15"
    - name: SETUP_MATLAB
      value: "true"
    - name: SETUP_MATHEMATICA
      value: ""
    - name: MOUNT_SRC
      value: "/usr/local/software"
    - name: POD_HTTP_PORT
      value: "8888"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "curl --insecure https://sciencedata/files/mathpass > /home/sciencedata/.WolframEngine/Licensing/mathpass >& /dev/null || echo 'no mathpass'"]
      preStop:
        exec:
          command: ["/bin/bash","-c","[ -s /home/sciencedata/.WolframEngine/Licensing/mathpass ] && curl --insecure --upload /home/sciencedata/.WolframEngine/Licensing/mathpass https://sciencedata/files/mathpass"]
