apiVersion: v1
kind: Pod
metadata:
  name: jupyter
spec:
  containers:
  - name: jupyter
    image: sciencedata/jupyter_sciencedata_custom:1.1
    volumeMounts:
      - name: local
        mountPath: "/cvmfs"
    ports:
    - containerPort: 8888
      protocol: TCP
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: SETUP_LCG
      value: "/cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-ubuntu2004-gcc9-opt/setup.sh"
    - name: MOUNT_SRC
      value: "/cvmfs"
    - name: POD_HTTP_PORT
      value: "8888"
    - name: FILE
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"

