apiVersion: v1
kind: Pod
metadata:
  name: nextcloud-dev
  labels:
    app: nextcloud-dev
spec:
  containers:
  - name: nextcloud-dev
    image: sciencedata/nextcloud_dev
    volumeMounts:
      - name: sciencedata
        mountPath: "/var/www"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "www"
    - name: SD_UID
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: HTTPS_PORT
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
