apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  containers:
  - name: nextcloud
    image: sciencedata/nextcloud
    volumeMounts:
      - name: sciencedata
        mountPath: "/var/www/nextcloud/data"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "www"
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: HTTPS_PORT
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
