apiVersion: v1
kind: Pod
metadata:
  name: worker
  annotations:
    sciencedata.dk/copy-token: "ed25519HostKeyHash,rsaHostKeyHash"
spec:
  containers:
  - name: worker
    image: LOCALREGISTRY/python_worker_sciencedata
    env:
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: ENVIRONMENT_FILE # ask
      value: ""
    - name: SSH_PUBLIC_KEY # ask
      value: ""
    - name: STAY_ALIVE_AFTER # ask
      value: ""
    - name: PYTHON_SCRIPT # ask require
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
