apiVersion: v1
kind: Pod
metadata:
  name: test-long-key
  annotations:
    longkey: "copyForFrontend"
    shortkey: "copyForFrontend"
spec:
  containers:
  - name: tester
    image: kube.sciencedata.dk:5000/test_long_key
  restartPolicy: Never
