apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-noble-versitygw
  labels:
    app: ubuntu-noble-versitygw
spec:
  containers:
  - name: ubuntu-noble-versitygw
    image: sciencedata/ubuntu_noble_versitygw_sciencedata
    volumeMounts:
      - name: sciencedata
        mountPath: "/mnt/vgw"
    ports:
    - containerPort: 7070
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: POD_HTTP_PORT
      value: "7070"
    - name: USERNAME
      value: "s3"
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    - name: NFS_RW
      value: "yes"
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
