apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-focal-cvmfs
spec:
  containers:
  - name: ubuntu-focal-cvmfs
    image: sciencedata/ubuntu_focal_sciencedata
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "sciencedata"
    - name: HOME_SERVER
      value: ""
    - name: SD_UID
      value: ""
    - name: SETUP_SCRIPT
      value: "/cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-ubuntu2004-gcc9-opt/setup.sh"
    - name: CVMFS_REPOS
      value: "atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch,unpacked.cern.ch,sft.cern.ch"
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  securityContext:
    sysctls:
    - name: "net.ipv4.ping_group_range"
      value: "0 2147483647"
  restartPolicy: Never

