apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  annotations:
    sciencedata.dk/copy-token: "ed25519HostKeyHash,rsaHostKeyHash"
spec:
  containers:
  - name: ubuntu-jammy
    image: LOCALREGISTRY/ubuntu_jammy_sciencedata
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY # ask require
      value: ""
    - name: USERNAME
      value: "root"
    - name: HOME_SERVER
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
  restartPolicy: Never
