apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  annotations:
    security.alpha.kubernetes.io/sysctls: net.ipv4.ping_group_range=0 2147483647
spec:
  containers:
  - name: ubuntu-jammy
    image: kube.sciencedata.dk:5000/ubuntu_jammy_sciencedata_testing
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "root"
    - name: HOME_SERVER
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
  restartPolicy: Never
