apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-jammy-caddy
  labels:
    app: ubuntu-jammy-caddy
spec:
  containers:
  - name: ubuntu-jammy-caddy
    image: sciencedata/ubuntu_jammy_caddy_sciencedata
    volumeMounts:
      - name: sciencedata
        mountPath: "/root/www"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
    - name: USERNAME
      value: "root"
    - name: HOME_SERVER
      value: ""
    - name: PUBLIC_HOME_SERVER
      value: ""
    securityContext:
      capabilities:
        add:
          - "SYS_CHROOT"
          - "AUDIT_WRITE"
          - "NET_ADMIN"
  restartPolicy: Never
